version: "3"
services:
  python-service:
    restart: always
    build: .
    container_name: "takohachi-bot"
    tty: true
    env_file:
      - .env
    volumes:
      - ./data/:/data/
      - ./logs/:/logs/
