[tool.poetry]
name = "takohachi"
version = "1.0.0"
description = "Gangsta Discord bot"
authors = ["Pistachio dev",]
maintainers = [
    "Yuki Koyama <email>",
    "zztkm <email>",
]
readme = "README.md"
license = "MIT"
repository = "https://github.com/pistachiostudio/takohachi"

[tool.poetry.dependencies]
python = "^3.11"
discord-py = {version = "2.1.0", extras = ["voice"]}
typing-extensions = "3.7.4.3"
gspread = "5.2.0"
requests = "2.25.1"
beautifulsoup4 = "4.10.0"
oauth2client = "4.1.3"
pydrive2 = "1.8.3"
spotipy = "2.19.0"
openai-async = "^0.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
