[tool.poetry]
name = "takohachi"
version = "1.0.0"
description = "Gangsta Discord bot"
authors = ["Pistachio dev",]
maintainers = [
    "Yuki Koyama <email>",
    "zztkm <email>",
]
readme = "README.md"
license = "MIT"
repository = "https://github.com/pistachiostudio/takohachi"

[tool.poetry.dependencies]
python = "^3.11"
discord-py = {version = "2.2.3", extras = ["voice"]}
typing-extensions = "3.10.0.2"
gspread = "5.2.0"
requests = "2.30.0"
beautifulsoup4 = "4.12.2"
oauth2client = "4.1.3"
pydrive2 = "1.15.3"
spotipy = "2.23.0"
httpx = "^0.23.3"
tenacity = "^8.2.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
