[tool.poetry]
name = "takohachi"
version = "0.1.0"
description = "Gangsta Discord bot"
authors = ["Pistachio dev"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
discord-py = {version = "2.0.1", extras = ["voice"]}
typing-extensions = "3.7.4.3"
gspread = "5.2.0"
beautifulsoup4 = "4.10.0"
oauth2client = "4.1.3"
pydrive2 = "1.8.3"
spotipy = "2.19.0"
requests = "^2.28.1"


[tool.poetry.group.dev.dependencies]
tox = "^4.2.3"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pre-commit = "^2.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
