# refs:
# - https://github.com/actions/setup-python
name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    env:
      USING_COVERAGE: "3.11"

    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.lock
    - name: Setup test suite
      run: tox -vv --notest
    - name: Run test suite
      run: tox --skip-pkg-install
