# refs:
# - https://github.com/actions/setup-python
name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    env:
      USING_COVERAGE: "3.12"

    strategy:
      matrix:
        platform: [ubuntu-24.04]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run Check
      run: uv run pre-commit run --all-files
    
    - name: Run Test
      run: uv run pytest tests
