name: takohachi deploy

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - name: SSH Remote Commands
            uses: appleboy/ssh-action@v0.1.5
            with:
              host: ${{ secrets.DEPLOY_HOST }}
              username: ${{ secrets.DEPLOY_USER }}
              port: ${{ secrets.DEPLOY_PORT }}
              key: ${{ secrets.DEPLOY_KEY }}
              script: |
                cd ${{ secrets.DEPLOY_DIR }}
                sudo git pull origin master
                docker compose up -d

