name: takohachi deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'images/**'
      - 'scripts/**'
      - '**.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - name: SSH Remote Commands
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ secrets.DEPLOY_HOST }}
              username: ${{ secrets.DEPLOY_USER }}
              port: ${{ secrets.DEPLOY_PORT }}
              key: ${{ secrets.DEPLOY_KEY }}
              script: |
                cd ${{ secrets.DEPLOY_DIR }}
                sudo git pull origin main
                sudo docker compose up -d --build --force-recreate
                sudo docker system prune -a -f
